### ISSUE TITLE
Can't update contract with `false` values.

### ISSUE THREAD

**Issue by rogefm** [nucleojs/nucleo#28]
When you call a update function, and pass `false` values like:
 - Empty strings, of string type
 - zero, of number type
 - false, of bool type

These values doesn't update the store, and return OK with the supposed new values. 
When this situation happens, was verified in the `indexSearch`, on `rec` and `save` methods inside `dataReflection` that, the validation of these new values use a conditional `OR` in javascript used like `||` and this don't let pass those `false` values, as said before.

<img width="584" alt="screen shot 2019-02-18 at 19 38 43" src="https://user-images.githubusercontent.com/8339935/52979599-0fe0d200-33b5-11e9-8cb8-358dc8f5dd68.png">

<img width="579" alt="screen shot 2019-02-18 at 19 38 50" src="https://user-images.githubusercontent.com/8339935/52979601-0fe0d200-33b5-11e9-972d-3f03d63f37fd.png">

**Comment by rogefm** [comment]
PR associated -> #29

**Comment by mtmr0x** [comment]
damn nice!
